# Generated by Django 5.0.4 on 2025-01-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordphrase',
            old_name='example_sentence',
            new_name='sentence_first_lang',
        ),
        migrations.RenameField(
            model_name='wordphrase',
            old_name='translation',
            new_name='word_first_lang',
        ),
        migrations.RenameField(
            model_name='wordphrase',
            old_name='word_phrase',
            new_name='word_second_lang',
        ),
        migrations.AddField(
            model_name='wordphrase',
            name='sentence_second_lang',
            field=models.TextField(blank=True, null=True),
        ),
    ]
